use_frameworks!

target 'ScanningQRCodeInMultiple_Example' do
  pod 'ScanningQRCodeInMultiple', :path => '../'

  target 'ScanningQRCodeInMultiple_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
